#!/usr/bin/env node
// ─────────────────────────────────────────────────────────────
// scrape_profiles.js — Headless scraper using saved cookies (Attempt 2 variant)
//
// Loads the session cookies saved by login.js and injects them into
// a headless browser to scrape profiles without going through login again.
//
// IMPORTANT: Run login.js first to generate linkedin_cookies.json.
//   LINKEDIN_EMAIL="your@email.com" LINKEDIN_PASSWORD="yourpassword" node login.js
//
// HOW TO RUN (after login.js):
//   node scrape_profiles.js
//
// HOW TO CONFIGURE TARGETS:
//   Edit the TARGETS array below. The slug is the last segment of a LinkedIn URL.
//   Example: linkedin.com/in/williamhgates → slug is 'williamhgates'
//
// NOTE ON BOT DETECTION:
//   LinkedIn's bot detection may still flag headless requests even with valid cookies.
//   If you get redirect loops or login pages instead of profiles, re-run login.js
//   to refresh the cookies, then try again.
//
// OUTPUT:
//   Console: Featured section links + PDF/resume links for each profile
// ─────────────────────────────────────────────────────────────

const puppeteer = require('puppeteer');
const fs = require('fs');
const path = require('path');

// Expects linkedin_cookies.json in the same directory — generated by login.js
const COOKIES_FILE = path.join(__dirname, 'linkedin_cookies.json');

// ── CONFIGURE YOUR TARGETS HERE ───────────────────────────────
// Add or remove objects in this array.
// name: display label used in console output (can be anything)
// slug: the LinkedIn URL slug for that person
const TARGETS = [
  { name: 'Example Person 1', slug: 'williamhgates' },
  { name: 'Example Person 2', slug: 'satya-nadella' },
];

(async () => {
  // Load cookies from disk — this file was saved by login.js
  const cookies = JSON.parse(fs.readFileSync(COOKIES_FILE, 'utf8'));

  // Run headless (no visible browser window) since we're not doing login
  const browser = await puppeteer.launch({ headless: true, args: ['--no-sandbox'] });
  const page = await browser.newPage();

  // Set a real user agent — headless Chrome has a default user agent that's easy to detect
  await page.setUserAgent(
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36'
  );

  // ── Inject saved cookies into the browser session ─────────
  // Map the cookie objects to the format Puppeteer's setCookie expects.
  // The domain must be set to .linkedin.com (with the leading dot) for
  // cookies to apply across all linkedin.com subdomains.
  await page.setCookie(...cookies.map(c => ({
    name: c.name,
    value: c.value,
    domain: c.domain || '.linkedin.com',
    path: c.path || '/',
    httpOnly: c.httpOnly || false,
    secure: c.secure || true,
  })));

  // ── Visit each target profile ─────────────────────────────
  for (const target of TARGETS) {
    console.log(`\n=== ${target.name} (linkedin.com/in/${target.slug}) ===`);
    try {
      await page.goto(`https://www.linkedin.com/in/${target.slug}/`, {
        waitUntil: 'networkidle2',
        timeout: 15000,
      });

      // Wait for dynamic content to settle after page load
      await new Promise(r => setTimeout(r, 2000));

      // Check if still logged in — the global nav search bar only exists when authenticated
      const loggedIn = await page.$('#global-nav-typeahead');
      console.log('Logged in:', !!loggedIn);

      // ── Extract Featured section links ─────────────────────
      // Searches all <section> elements for one with an h2 containing "featured"
      const featured = await page.evaluate(() => {
        const sections = Array.from(document.querySelectorAll('section'));
        for (const sec of sections) {
          const heading = sec.querySelector('h2');
          if (heading && heading.textContent.trim().toLowerCase().includes('featured')) {
            return Array.from(sec.querySelectorAll('a[href]')).map(a => ({
              text: a.textContent.trim().slice(0, 80),
              href: a.href,
            }));
          }
        }
        return [];
      });

      if (featured.length === 0) {
        console.log('No Featured section found');
      } else {
        featured.forEach(f => console.log(' -', f.text, '->', f.href));
      }

      // ── Also scan the full page for resume/PDF links ───────
      // Catches links to PDFs, pages with "resume" or "portfolio" in the URL
      const pdfLinks = await page.evaluate(() =>
        Array.from(document.querySelectorAll('a[href*=".pdf"], a[href*="resume"], a[href*="portfolio"]'))
          .map(a => ({ text: a.textContent.trim().slice(0, 60), href: a.href }))
      );

      if (pdfLinks.length > 0) {
        console.log('PDF/Resume links:');
        pdfLinks.forEach(l => console.log(' -', l.text, '->', l.href));
      }

    } catch (e) {
      console.log('Error:', e.message);
    }

    // Pause between profiles — reduces chance of rate limiting
    await new Promise(r => setTimeout(r, 3000));
  }

  await browser.close();
})();
